server:
  port: 9092

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

security:
    oauth2:
        client:
            access-token-validity-seconds: 1800
            authorized-grant-types: password,refresh_token
            client-id: coderef
            client-secret: $2a$10$pHrkc/kyN4xfkI4T5D/RZOTRIOHbHNqOhmPis7fIotaSyswQcMadi
            resource-ids: resources
            scope: read,write

spring:
    datasource:
        #schema: classpath:/sql/schema.sql
        #data: classpath:/sql/data.sql
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.209:3306/oauth?allowPublicKeyRetrieval=TRUE&useSSL=FALSE
        platform: mysql
        username: root
        password: root        
        
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: create
        show-sql: true
